name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build PicoStreamingAssistantFTUDP/PicoStreamingAssistantFTUDP.sln --configuration Release
      - name: Find DLLs
        run: find . -name "*.dll" -path "*/Release/*"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pico4SAFTExtTrackingModule
          path: '**/bin/Release/**/*.dll'
